# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile Java Classes
        run: 
          cd Projects/P2
          ./gradlew build testClasses -x test

  pacman_in_range:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Pacman In Range
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManInRange
  ghost_in_range:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Ghost In Range
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostInRange
  map_attack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Map
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapAttack
  pacman_valid_moves:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Pacman In Range
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManValidMoves
  ghost_valid_moves:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Ghost In Range wow
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostValidMoves
		  
  map_move:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Map
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapMove
  Pacman_consume:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Pacman In Range
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManConsume
		  
  Ghost_attack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Ghost In Range
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostAttack
		  
  Map_eatCookie:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Map
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapEatCookie
  Pacman_move:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Pacman Move
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManMove
		  
  Ghost_move:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Ghost Move
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostMove
		  
  Map_getLoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test Map Get Loc
        run: |
          cd Projects/P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapGetLoc
