name: deployment workflow
on: 
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ HOST }} 
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}
          port: ${{ PORT }}
          script: |
              gradle build
              gradle test --parallel

